import { images } from "../constants";

const categories = [
  { id: "001a", title: "Main Course" },
  { id: "002a", title: "Side Dish" },
  { id: "003a", title: "Dessert" },
  { id: "004a", title: "Appetizer" },
  { id: "005a", title: "Salad" },
  { id: "006a", title: "Bread" },
  { id: "007a", title: "Breakfast" },
  { id: "008a", title: "Soup" },
  { id: "009a", title: "Beverage" },
  { id: "010a", title: "Sauce" },
  { id: "011a", title: "Marinade" },
  { id: "012a", title: "Fingerfood" },
  { id: "013a", title: "Snack" },
  { id: "014a", title: "Drink" },
];

const filters = [
  {
    title: "Cuisine",
    data: [
      { id: 1, name: "African" },
      { id: 2, name: "Asian" },
      { id: 3, name: "American" },
      { id: 4, name: "British" },
      { id: 5, name: "Cajun" },
      { id: 6, name: "Caribbean" },
      { id: 7, name: "Chinese" },
      { id: 8, name: "Eastern European" },
      { id: 9, name: "European" },
      { id: 10, name: "French" },
      { id: 11, name: "German" },
      { id: 12, name: "Greek" },
      { id: 13, name: "Indian" },
      { id: 14, name: "Irish" },
      { id: 15, name: "Italian" },
      { id: 16, name: "Japanese" },
      { id: 17, name: "Jewish" },
      { id: 18, name: "Korean" },
      { id: 19, name: "Latin American" },
      { id: 20, name: "Mediterranean" },
      { id: 21, name: "Mexican" },
      { id: 22, name: "Middle Eastern" },
      { id: 23, name: "Nordic" },
      { id: 24, name: "Southern" },
      { id: 25, name: "Spanish" },
      { id: 26, name: "Thai" },
      { id: 27, name: "Vietnamese" },
    ],
  },
  {
    title: "Type",
    data: [
      { id: "001a", name: "Main Course" },
      { id: "002a", name: "Side Dish" },
      { id: "003a", name: "Dessert" },
      { id: "004a", name: "Appetizer" },
      { id: "005a", name: "Salad" },
      { id: "006a", name: "Bread" },
      { id: "007a", name: "Breakfast" },
      { id: "008a", name: "Soup" },
      { id: "009a", name: "Beverage" },
      { id: "010a", name: "Sauce" },
      { id: "011a", name: "Marinade" },
      { id: "012a", name: "Fingerfood" },
      { id: "013a", name: "Snack" },
      { id: "014a", name: "Drink" },
    ],
  },
];

const ingredients = [
  {
    title: "ingredients",
    data: [
      { id: "A1", name: "Butter" },
      { id: "A2", name: "Eggs" },
      { id: "A3", name: "Garlic" },
      { id: "A4", name: "Milk" },
      { id: "A5", name: "Onion" },
      { id: "A6", name: "Sugar" },
      { id: "A7", name: "Flour" },
      { id: "A8", name: "Olive oil" },
      { id: "A9", name: "White rice" },
      { id: "A10", name: "Cinnamon" },
      { id: "A11", name: "Garlic powder" },
      { id: "A12", name: "Ketchup" },
      { id: "A13", name: "Soy sauce" },
      { id: "A14", name: "Oil" },
      { id: "A15", name: "Water" },
      { id: "A16", name: "Honey" },
      { id: "A17", name: "Potato" },
    ]
  },
];

const types = [
  {
    title: "categories",
    data: [
      { id: "001a", name: "Main Course" },
      { id: "002a", name: "Side Dish" },
      { id: "003a", name: "Dessert" },
      { id: "004a", name: "Appetizer" },
      { id: "005a", name: "Salad" },
      { id: "006a", name: "Bread" },
      { id: "007a", name: "Breakfast" },
      { id: "008a", name: "Soup" },
      { id: "009a", name: "Beverage" },
      { id: "010a", name: "Sauce" },
      { id: "011a", name: "Marinade" },
      { id: "012a", name: "Fingerfood" },
      { id: "013a", name: "Snack" },
      { id: "014a", name: "Drink" },
    ],
  },
];

const cuisine = [
  {
    title: "cuisine",
    data: [
      { id: 1, name: "African" },
      { id: 2, name: "Asian" },
      { id: 3, name: "American" },
      { id: 4, name: "British" },
      { id: 5, name: "Cajun" },
      { id: 6, name: "Caribbean" },
      { id: 7, name: "Chinese" },
      { id: 8, name: "Eastern European" },
      { id: 9, name: "European" },
      { id: 10, name: "French" },
      { id: 11, name: "German" },
      { id: 12, name: "Greek" },
      { id: 13, name: "Indian" },
      { id: 14, name: "Irish" },
      { id: 15, name: "Italian" },
      { id: 16, name: "Japanese" },
      { id: 17, name: "Jewish" },
      { id: 18, name: "Korean" },
      { id: 19, name: "Latin American" },
      { id: 20, name: "Mediterranean" },
      { id: 21, name: "Mexican" },
      { id: 22, name: "Middle Eastern" },
      { id: 23, name: "Nordic" },
      { id: 24, name: "Southern" },
      { id: 25, name: "Spanish" },
      { id: 26, name: "Thai" },
      { id: 27, name: "Vietnamese" },
    ],
  },
];
const diet = [
  {
    title: "diet",
    data: [
      { id: 1, name: "Gluten Free" },
      { id: 2, name: "Ketogenic" },
      { id: 3, name: "Vegetarian" },
      { id: 4, name: "Lacto-Vegetarian" },
      { id: 5, name: "Ovo-Vegetarian" },
      { id: 6, name: "Vegan" },
      { id: 7, name: "Pescetarian" },
      { id: 8, name: "Paleo" },
      { id: 9, name: "Primal" },
      { id: 10, name: "Low FODMAP" },
      { id: 11, name: "Whole30" },
    ],
  },
];

const notifications = [
  {
    id: "9900a",
    title: "New Recipe",
    message: "Far far away, behind the word mountains, far from the countries.",
    read: false,
    date: "09/25/2024",
  },
  {
    id: "9901a",
    title: "Don't forget to try your saved recipe",
    message: "Far far away, behind the word mountains, far from the countries.",
    read: false,
    date: "09/25/2024",
  },
  {
    id: "9902a",
    title: "Don't forget to try your saved recipe",
    message: "Far far away, behind the word mountains, far from the countries.",
    read: true,
    date: "08/25/2024",
  },
];
const measurement = [
  { label: "Teaspoon", value: "tsp" },
  { label: "Tablespoon", value: "tbs" },
  { label: "Cup", value: "cup" },
  { label: "Milliliter", value: "ml" },
  { label: "Liter", value: "l" },
  { label: "Gram", value: "gr" },
  { label: "Kilogram", value: "kg" },
];

export {
  categories,
  notifications,
  measurement,
  filters,
  ingredients,
  diet,
  cuisine,
  types,
};
{/* 
{ id: "B2", name: "Onion" },
{ id: "B3", name: "Bell peppers" },
{ id: "B4", name: "Carrot" },
{ id: "B5", name: "Tomatoes" },
{ id: "B6", name: "Scallions" },
{ id: "B7", name: "Potato" },
{ id: "B8", name: "Celery" },
{ id: "B9", name: "Zucchini" },
{ id: "B10", name: "Avocado" },
{ id: "B11", name: "Shallot" },
{ id: "B12", name: "Cucumber" },
{ id: "B13", name: "Spinach" },
{ id: "B14", name: "Sweet corn" },
{ id: "B15", name: "Cabbage" },
{ id: "B16", name: "Pumpkin" },
{ id: "B17", name: "Asparagus" },
{ id: "B18", name: "Broccoli" },
{ id: "C1", name: "Apples" },
{ id: "C2", name: "Oranges" },
{ id: "C3", name: "Banana" },
{ id: "C4", name: "Lemon" },
{ id: "C5", name: "Lime" },
{ id: "C6", name: "Raisins" },
{ id: "C7", name: "Pineapple" },
{ id: "C8", name: "Dates" },
{ id: "C9", name: "Pomegranate" },
{ id: "C10", name: "Pears" },
{ id: "C11", name: "Grapes" },
{ id: "C12", name: "Coconut" },
{ id: "C13", name: "Peach" },
{ id: "C14", name: "Watermelon" },
{ id: "C15", name: "Plums" },
{ id: "C16", name: "Apricot" },
{ id: "C17", name: "Prunes" },
{ id: "C18", name: "Fig" },
{ id: "D1", name: "Butter" },
{ id: "D2", name: "Eggs" },
{ id: "D3", name: "Milk" },
{ id: "D4", name: "Heavy cream" },
{ id: "D5", name: "Buttermilk" },
{ id: "D6", name: "Sour cream" },
{ id: "D7", name: "Greek yogurt" },
{ id: "D8", name: "Cream" },
{ id: "D9", name: "Ghee" },
{ id: "D10", name: "Condensed milk" },
{ id: "D11", name: "Ice cream" },
{ id: "D12", name: "Margarine" },
{ id: "D13", name: "Frosting" },
{ id: "D14", name: "Milk powder" },
{ id: "D15", name: "Curd" },
{ id: "D16", name: "Shortening" },
{ id: "D17", name: "Custard" },
{ id: "D18", name: "Kefir" },
 */}